version: "3.8"
services:
  postgres:
    image: pgvector/pgvector:0.7.0-pg16
    container_name: pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: localdb
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "localdb"]
      interval: 5s
      timeout: 60s
      retries: 5

  ollama-api-local:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  pgvector_data:
  ollama_data:
