spring:
  application:
    name: springai-api-local

  datasource:
    url: jdbc:postgresql://localhost:5432/localdb
    username: postgres
    password: postgres
  ai:
    retry:
      backoff:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 4
      max-attempts: 20
    ollama:
      embedding:
        model: nomic-embed-text
        options:
          top-k: 10
          num-thread: 8
          num-ctx: 8192
          num-batch: 768
          top-p: 1
        enabled: true
      base-url: http://localhost:11434
      chat:
        model: mistral
        options:
          num-ctx: 2048
          num-batch: 768
          num-thread: 8
          top-k: 1
          top-p: 1
          temperature: 0.5
    vectorstore:
      pgvector:
        index-type: hnsw
        dimensions: 768
        distance-type: COSINE_DISTANCE
